apiVersion: v1
kind: ServiceAccount
metadata:
 namespace: fogflow
 name: fogflow-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: fogflow
 name: fogflow-dns-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list","create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 namespace: fogflow
 name: fogflow-dns-viewer
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: fogflow-dns-role
subjects:
- kind: ServiceAccount
  namespace: fogflow
  name: fogflow-dns-role

