apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: designer
  name: designer
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "1030"
    port: 1030
    targetPort: 1030
  selector:
    io.kompose.service: designer
  externalIPs:
  - 172.30.48.24
status:
  loadBalancer: {}
