version: "2"

networks:
    idm_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.1.0/24
                  gateway: 172.18.1.1

services:
    pep-proxy:
        image: fiware/pep-proxy
        ports:
            - "5555:5555"
        volumes:
            - ./pep_config.js:/opt/fiware-pep-proxy/config.js

