#Namespace for all components
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }} 
---
#service account for all components in fogflow namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccount }}
---
#ClusterRole fogflow-dns creation for all components in fogflow namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.namespace }}
  name: fogflow-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list","create"]
---
#ClusterRoleBinding for all components fogflow-dns in fogflow namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: fogflow-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fogflow-dns
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}

