version: "3.5"
services:     
    elasticsearch:
        image: elasticsearch:7.5.1
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - discovery.type=single-node
    
    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.6.0
        user: root
        volumes:
          - ./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml
          - /var/run/docker.sock:/var/run/docker.sock
          - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
          - /proc:/hostfs/proc
          - /:/hostfs
    
    grafana:
        image: grafana/grafana:6.5.0
        links:
          - elasticsearch
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
          - ./grafana.yaml:/etc/grafana/provisioning/dashboards/default.yaml
          - ./dashboards:/var/lib/grafana/dashboards
        depends_on:
          - elasticsearch
        ports:
          - "3003:3000"
        restart: always
