# Default values for fogflow-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Kubernetes namespace of FogFlow components 
namespace: fogflow 

#replicas will make sure that no. of replicaCount mention in values.yaml
# are running all the time for the deployment
replicaCount: 1

#hostPath for dgraph volume mount
dgraph:
  hostPath:
    path: /dgraph

#hostPath for config.json  
configJson:
  hostPath:
    path: /root/co-28/fogflow/helm/fogflow-chart/config.json

#hostPath for nginx.conf 
nginxConf:
  hostPath:
    path: /root/co-28/fogflow/helm/fogflow-chart/nginx.conf 

Service:
 spec: 
  externalIPs: 
  - 172.30.48.24 
