apiVersion: v1
kind: PersistentVolume
metadata:
  name: dgraph-claim0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/dgraph
    server: 172.30.76.68
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dgraph-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
