apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dgraph
  name: dgraph
spec:
  ports:
  - name: "6080"
    port: 6080
    #    targetPort: 6080
  - name: "8080"
    port: 8082
    # targetPort: 8082
  - name: "9080"
    port: 9082
    #targetPort: 9082
  - name: "8000"
    port: 8000
    # targetPort: 8000
  selector:
    io.kompose.service: dgraph
  externalIPs:
  - 172.30.48.24  
status:
  loadBalancer: {}
