apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cloud-broker
  name: cloud-broker
spec:
  ports:
  - name: "8070"
    port: 8070
    targetPort: 8070
  selector:
    io.kompose.service: cloud-broker
  externalIPs:
  - 172.30.76.63
status:
  loadBalancer: {}
