apiVersion: apps/v1
kind: ClusterRole
metadata:
    annotations:
       rbac.authorization.kubernetes.io/autoupdate: “true”
       creationTimestamp: null
       labels:
         kubernetes.io/bootstrapping: rbac-defaults
         name: cloud-worker
  rules:
      - apiGroups:
      - ‘*’
      resources:
       - ‘*’
       verbs:
       - ‘*’
